### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [11]:
from random import *

l1 = []
for i in range (100, 122, 2):
    l1.append(chr(i))
l1lc = [chr(i) for i in range (100, 122, 2)]

print(l1, l1lc)

l2 = []
for i in range(9):
    if i**i < 1000:
        l2.append(i**i)
l2lc = [i**i for i in range (39) if i**i < 1000]

print(l2, l2lc)

l3 = []
m = randint(2, 50)
while m != 22:
    l3.append(m)
    m = randint(2, 50)

def whl ():
    m = randint(2, 50)
    while m != 22:
        yield m
        m = randint(2, 50)

l3lc = [i for i in whl()]

print (l3, l3lc)


['d', 'f', 'h', 'j', 'l', 'n', 'p', 'r', 't', 'v', 'x'] ['d', 'f', 'h', 'j', 'l', 'n', 'p', 'r', 't', 'v', 'x']
[1, 1, 4, 27, 256] [1, 1, 4, 27, 256]
[47, 50, 11, 4, 30, 16, 24, 32, 39, 42, 28, 33, 15] [32, 16, 42, 48, 33, 19, 37, 44, 44, 24, 7, 24, 10, 14, 40, 8, 48, 32, 38, 2, 50, 29, 23, 39, 10, 7, 39, 14, 14, 46, 17, 32, 35, 43, 37, 49, 28, 21, 12, 36, 7, 29, 5, 10, 35, 43, 34, 14, 50, 25, 34, 19, 15, 29, 14, 37, 30, 10, 21, 47, 50, 14, 31, 33, 32, 36, 35, 10, 32, 47, 5, 6, 34, 36, 4, 38, 20, 42, 34, 18, 15, 27, 38, 16, 37, 37, 8, 27, 26, 20, 11, 45, 14, 3, 12, 31, 14, 49, 37, 4, 39, 4, 37, 20, 11, 8, 46, 47, 20, 13, 47, 9, 40, 6, 18, 10, 14, 18, 23, 20, 7, 8, 17, 8, 6, 5, 48, 43, 11, 43, 34, 4, 8, 27, 9, 39, 32, 27, 6]


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [ ]:
import numpy
from math import *

l1 = []
for i in range (2, 10):
    pr = True
    for j in range (2, i):
        if i % j == 0:
            pr = False
    if pr:
        l1.append(i)
a1 = numpy.array(l1)
print(a1, len(a1), a1.size)
#dtype ritornera il tipo del vettore (int) seguito dalla grandezza in bit di ogni elemento (64)
a1.dtype #INT 32?!?!?!

a1lc = numpy.array([x for x in range(2, 10) if  all(x % y != 0 for y in range(2, x))])
print(a1lc)

[2 3 5 7] 4 4
[2 3 5 7]


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [15]:
import numpy
a = numpy.array([x for x in range(2, 10) if  all(x % y != 0 for y in range(2, x))])
b = numpy.array("fwey")
c = numpy.flip(a)
print(a, b, c)
print(a/c)
la = [x for x in range(2, 10) if  all(x % y != 0 for y in range(2, x))]
lb = list("fwey")
lc = la[::-1]
print(la, lb, lc)
for i in range(len(la)):
    print(la[i] / lc[i], end = " ")

[2 3 5 7] fwey [7 5 3 2]
[0.28571429 0.6        1.66666667 3.5       ]
[2, 3, 5, 7] ['f', 'w', 'e', 'y'] [7, 5, 3, 2]
0.2857142857142857 0.6 1.6666666666666667 3.5 